In [12]:
import sys
import os
sys.path.append(os.path.abspath('..'))

import pandas as pd
import numpy as np
from pathlib import Path
from TPT_generator_python import DataBucket, TPTFetcher, TPTGenerator
from TPT_generator_python.constants import RATINGS

In [13]:
DATE = "2020-12-31"
CLIENT = "Dynasty"
ISIN = "LU1280365476"
SYMADJ = -0.48
SOURCE_DIR = Path("../data")
OUTPUT_DIR = './production/example'
ALL = slice(None)

In [14]:
generator = TPTGenerator(DATE,
                         CLIENT,
                         OUTPUT_DIR,
                         SOURCE_DIR,
                         sym_adj=SYMADJ,
                         shareclass_isin=ISIN)
generator

    Reporting date:          2020-12-31
    Client:                  Dynasty
    Shareclass isin:         LU1280365476
    number of instruments:   137

In [51]:
ratings = generator.data_bucket.get_instruments(['rating_moodys','rating_sp','rating_fitch'])
ratings = ratings.loc[~(ratings.isnull().all(axis=1))]
ratings.replace({"u": "",
                 "p": "",
                 " \*+": "",
                 " \*-": "",
                 "e": ""}, regex=True, inplace=True)
ratings.replace("WD", None, regex=True, inplace=True)
ratings

             rating_moodys rating_sp rating_fitch
instrument
CH0413990240          None        A-         None
DE000A2AAQB8          None      None          BBB
DE000A2DAHU1          Baa3       BBB         BBB-
FR0011076439          None         A            A
US472145AB79          None        B+         None
US741503AX44          None        A-         None
US92343XAA81          None       BB-         None
XS0468425615          Baa2      BBB+          BBB
XS0592505316          Baa1      BBB+          BBB
XS1377251423          Baa3      BBB-          BBB
XS1394957309          Baa1        A-           A-
XS1434160971            A2         A         None
XS1521058518            A2        A-            A
XS1548436556            A2         A         None
XS1571293171           Ba1      BBB-         BBB-
XS1637272342          None      BBB+         BBB+
XS1713466578          Baa3       BBB          BBB
XS1806453814            A3      BBB+         None
XS1843436491          Baa2       BBB          BBB
XS1881591504            A3      None         None
XS1919894813          None       BB-         None
XS2038088527           Aa2      None         None
XS2194282948          None      BBB-         None
XS2257580857          None      None         BBB-
XS2269112863          Baa2      None         None

In [100]:
def func(x, y):
    if y is not None: 
        return RATINGS[x.name][y]
    
def sort_and_select_func(list_val):
    list_val.sort()
    return list_val[-2]

CQS = ratings.apply(lambda x: x.apply(lambda y: func(x,y)))
CQS["CQS"] = CQS.apply(lambda x: x.dropna().tolist(), axis=1)
CQS["CQS"].values.sort()
CQS

              rating_moodys  rating_sp  rating_fitch              CQS
instrument
CH0413990240            NaN        2.0           NaN            [1.0]
DE000A2AAQB8            NaN        NaN           3.0            [2.0]
DE000A2DAHU1            3.0        3.0           3.0            [2.0]
FR0011076439            NaN        2.0           2.0            [2.0]
US472145AB79            NaN        5.0           NaN       [2.0, 2.0]
US741503AX44            NaN        2.0           NaN       [2.0, 2.0]
US92343XAA81            NaN        4.0           NaN       [2.0, 2.0]
XS0468425615            3.0        3.0           3.0  [2.0, 2.0, 2.0]
XS0592505316            3.0        3.0           3.0       [2.0, 3.0]
XS1377251423            3.0        3.0           3.0            [3.0]
XS1394957309            3.0        2.0           2.0            [3.0]
XS1434160971            2.0        2.0           NaN            [3.0]
XS1521058518            2.0        2.0           2.0            [3.0]
XS1548436556            2.0        2.0           NaN  [3.0, 2.0, 2.0]
XS1571293171            4.0        3.0           3.0       [3.0, 3.0]
XS1637272342            NaN        3.0           3.0  [3.0, 3.0, 3.0]
XS1713466578            3.0        3.0           3.0  [3.0, 3.0, 3.0]
XS1806453814            2.0        3.0           NaN  [3.0, 3.0, 3.0]
XS1843436491            3.0        3.0           3.0  [3.0, 3.0, 3.0]
XS1881591504            2.0        NaN           NaN  [3.0, 3.0, 3.0]
XS1919894813            NaN        4.0           NaN  [3.0, 3.0, 3.0]
XS2038088527            1.0        NaN           NaN            [4.0]
XS2194282948            NaN        3.0           NaN            [4.0]
XS2257580857            NaN        NaN           3.0  [4.0, 3.0, 3.0]
XS2269112863            3.0        NaN           NaN            [5.0]